name: Rust

on:
  push:
    branches: ["main", "ghactions"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pgrx
        run: |
          cargo install --locked cargo-pgrx
          cargo pgrx init

      - name: Run pgrx tests
        run: cargo pgrx test
